#
# Module manifest for module 'ApexSQL_DevOps_toolkit'
#
# Generated by: Quest Software Inc
#
# Generated on: 11/19/2019
#

@{

# Script module or binary module file associated with this manifest
RootModule = "ApexSQL_DevOps_toolkit.psm1"

# Version number of this module.
ModuleVersion = '2019.04.0191'

# ID used to uniquely identify this module
GUID = '7af66d71-a22b-46bf-8a62-ad1e2d684eab'

# Author of this module
Author = 'Quest Software Inc'

# Company or vendor of this module
CompanyName = 'Quest Software Inc'

# Copyright statement for this module
Copyright = '© 2019 Quest Software Inc. ALL RIGHTS RESERVED.'

# Description of the functionality provided by this module
Description = 'The ApexSQL DevOps toolkit is a set of components and scripts that integrate with ApexSQL SQL developer tools to create SQL Server database continuous integration and delivery automation pipelines. The PowerShell functions provide SQL Server DevOps capability to any Windows environment.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Functions to export from this module
FunctionsToExport = @(
    "New-ApexSqlDatabaseConnection",
    "New-ApexSqlGitSourceControlConnection",
    "New-ApexSqlTfsSourceControlConnection",
    "New-ApexSqlMercurialSourceControlConnection",
    "New-ApexSqlSubversionSourceControlConnection",
    "New-ApexSqlPerforceSourceControlConnection",
    "New-ApexSqlFileConnection",
    "New-ApexSqlSFConnection",
    "New-ApexSqlSource",
    "New-ApexSqlNotificationSettings",
    "New-ApexSqlOptions",
    "GetSourceName",
    "GetSourceForDataDiff",
    "Initialize-Globals",
    "Invoke-ApexSqlAuditStep",
    "Invoke-ApexSqlBuildStep",
	"Invoke-ApexSqlCompareStep",
    "Invoke-ApexSqlDeployStep",
    "Invoke-ApexSqlDocumentStep",
	"Invoke-ApexSqlReviewStep",
	"Invoke-ApexSqlMaskStep",
    "Invoke-ApexSqlNotifyStep",
    "Invoke-ApexSqlPopulateStep",
    "Invoke-ApexSqlScriptStep",
    "Invoke-ApexSqlPackageStep",
    "Invoke-ApexSqlDataSyncStep",
    "Invoke-ApexSqlSchemaSyncStep",
    "Invoke-ApexSqlTestStep"
)

# Cmdlets to export from this module
CmdletsToExport = @()

# HelpInfo URI of this module
# HelpInfoURI = ''

}